prod_db_product_variant = [
    {"slug": "alulafpv-5-inch", "name": "AlulaFPV 5-Inch"},
    {"slug": "adl30", "name": "ADL30"},
    {"slug": "adl36", "name": "ADL36"},
    {"slug": "7-turn", "name": "7-Turn"},
    {"slug": "lhcp10-cm", "name": "LHCP(10 cm)"},
    {"slug": "rhcp-angle-15cm", "name": "RHCP angle (15cm)"},
    {"slug": "rhcp-15cm", "name": "RHCP (15cm)"},
    {"slug": "rhcp10cm", "name": "RHCP(10cm)"},
    {"slug": "lhcp-15cm", "name": "LHCP (15cm)"},
    {"slug": "vapor-x5", "name": "Vapor X5"},
    {"slug": "rrotek35", "name": "RroTek35"},
    {"slug": "m-5-props-nuts-4pcs", "name": "M-5 props Nuts (4pcs)"},
    {"slug": "foxwhoop", "name": "foxwhoop"},
    {"slug": "lhcp", "name": "LHCP"},
    {"slug": "jhe20b-finder", "name": "jHE20B  Finder"},
    {"slug": "xt-60-e", "name": "XT-60 E"},
    {"slug": "elrs-915mhz", "name": "ELRS-915MHz"},
    {"slug": "elrs-lite-rx", "name": "ELRS Lite RX"},
    {"slug": "prop-tool", "name": "Prop Tool"},
    {"slug": "baby-ratel-2", "name": "Baby Ratel 2"},
    {"slug": "8cm-cable", "name": "8cm cable"},
    {"slug": "black", "name": "black"},
    {"slug": "white", "name": "white"},
    {"slug": "dmkr-fpv-monitor", "name": "DMKR FPV Monitor"},
    {"slug": "peach-pink", "name": "Peach Pink"},
    {"slug": "yellow", "name": "Yellow"},
    {"slug": "er8", "name": "ER8"},
    {"slug": "ble-nano-3", "name": "BLE Nano 3"},
    {"slug": "nano-rx", "name": "Nano Rx"},
    {"slug": "evo", "name": "Evo"},
    {"slug": "1800kv-2207-motors", "name": "1800KV 2207 Motors"},
    {"slug": "58ghz-linear-antenna", "name": "5.8GHZ  Linear Antenna"},
    {"slug": "915-mhz-antenna", "name": "915 MHz Antenna"},
    {"slug": "9045", "name": "9045"},
    {"slug": "8060", "name": "8060"},
    {"slug": "8040", "name": "8040"},
    {"slug": "7060", "name": "7060"},
    {"slug": "5050", "name": "5050"},
    {"slug": "6055", "name": "6055"},
    {"slug": "7050", "name": "7050"},
    {"slug": "1280e", "name": "1280E"},
    {"slug": "1-8s-battery-checker", "name": "1-8S Battery Checker"},
    {"slug": "buzzer", "name": "Buzzer"},
    {"slug": "unicorn", "name": "3-Turn"},
    {"slug": "4", "name": "RHCP"},
    {
        "slug": "jhemcu-ghf722-hd-aio-fcesc-40a-255-x-255mm",
        "name": "JHEMCU GHF722 HD AIO",
    },
    {"slug": "10x6e", "name": "1060E"},
    {"slug": "airplane-propellers", "name": "9060"},
    {"slug": "dual-band-t-antenna", "name": "Dual-band T Antenna"},
    {"slug": "xt60-to-xt30-hctrh", "name": "XT60 to XT30"},
    {"slug": "camera", "name": "PHOENIX"},
    {"slug": "red-dbxku", "name": "Red"},
    {"slug": "adl36-rtfn", "name": "Neon"},
    {"slug": "camera-plate-soft-mount", "name": "Camera Plate Soft Mount"},
    {"slug": "60w", "name": "60W"},
    {"slug": "hop-up-opions-car-light", "name": "Hop up opions car light"},
    {"slug": "6s", "name": "6S"},
    {"slug": "lipo-bag", "name": "Lipo bag"},
    {"slug": "xt60-to-type-c-100w-pd-cable", "name": "XT60 to Type-C 100W PD Cable"},
    {
        "slug": "xt60-to-xt30-charging-adapter-without-cable",
        "name": "XT60 to XT30 Charging Adapter without cable",
    },
    {"slug": "20cm", "name": "20cm"},
    {"slug": "8cm", "name": "8cm"},
    {"slug": "15cm", "name": "15cm"},
    {"slug": "o4-heatsink", "name": "O4 Heatsink"},
    {"slug": "gopro-filters", "name": "Gopro Filters"},
    {"slug": "vtx-1000-v23", "name": "VTX 1000 V2.3"},
    {"slug": "elrs-24g-7-channel-pwm", "name": "ELRS 2.4G 7 Channel  PWM"},
    {"slug": "nano-2400-rx", "name": "Nano 2400 RX"},
    {"slug": "45a-esc", "name": "45A ESC"},
    {"slug": "pandarc-led-strip-5v-led-0539", "name": "PandaRC Led Strip 5V LED-0539"},
    {"slug": "4s", "name": "15mmX220mm for 4S battery"},
    {"slug": "5-nd-filters-set", "name": "5 ND Filters Set"},
    {"slug": "teal", "name": "Teal"},
    {"slug": "3clear-gray", "name": "3.5(Clear Gray )"},
    {"slug": "35pink", "name": "3.5(pink)"},
    {"slug": "purple", "name": "3.6 ( purple)"},
    {"slug": "clear-gray", "name": "3.6(Clear Gray)"},
    {"slug": "clear-green", "name": "3.6(Clear Green)"},
    {"slug": "7-black-durable", "name": "7 (Black Durable)"},
    {"slug": "7-light-grey", "name": "7 (Light Grey)"},
    {"slug": "t63mmx6gr-pc-tmount", "name": "T63MMX6GR-PC-Tmount"},
    {"slug": "4x200mm-black", "name": "4mmX200mm Black"},
    {"slug": "white-dkxen", "name": "White"},
    {"slug": "black-uqhsg", "name": "Black"},
    {"slug": "goggles2-cable", "name": "Goggles2 Cable"},
    {"slug": "black-dbffh", "name": "black"},
    {"slug": "nd8", "name": "ND8"},
    {"slug": "gopro-bag", "name": "Gopro Bag"},
    {"slug": "5-packets", "name": "5 packets"},
    {"slug": "5-pb-j", "name": "1 packet"},
    {"slug": "1300kv", "name": "4pcs 1300KV"},
    {"slug": "5115kv", "name": "900KV"},
    {"slug": "es08maii", "name": "ES08MAII"},
    {"slug": "xa22121400kv", "name": "XA2212/1400kv"},
    {"slug": "tattu-v50", "name": "Tattu V5.0, 1400mAh, 6S, 150C"},
    {"slug": "tattu-850mah-v50-150c", "name": "Tattu V5.0, 6S, 850mAh, 150C"},
    {"slug": "tattu-1480-st-oycag", "name": "Tattu 850"},
    {"slug": "beta-fpv", "name": "550 mAh"},
    {"slug": "imars-d300", "name": "Black"},
    {"slug": "imarsd300", "name": "White"},
    {"slug": "18650", "name": "18650"},
    {"slug": "2s", "name": "2s"},
    {"slug": "d6-pro", "name": "D6 pro"},
    {"slug": "t8", "name": "T8"},
    {"slug": "d100neo", "name": "D100neo"},
    {"slug": "2207", "name": "2207"},
    {"slug": "motor", "name": "1855KV"},
    {"slug": "t12", "name": "T12"},
    {"slug": "3800kv", "name": "4pcs - 3800kv"},
    {"slug": "adl36-rtf", "name": "Green"},
    {"slug": "dual-band-t-antenna-zyyaq", "name": "Dual-Band T Antenna"},
    {"slug": "xt60-to-xt30", "name": "XT60 to XT30"},
    {"slug": "red", "name": "Red"},
    {"slug": "neon", "name": "Nazgul F5"},
]

uat_db_product_variant = [
    {"slug": "lhcp10-cm", "name": "LHCP(10 cm)"},
    {"slug": "alulafpv-5-inch", "name": "AlulaFPV 5-Inch"},
    {"slug": "tattu-1480-st-oycag", "name": "Tattu 850"},
    {"slug": "rhcp-angle-15cm", "name": "RHCP angle (15cm)"},
    {"slug": "7-turn", "name": "7-Turn"},
    {"slug": "beta-fpv", "name": "550 mAh"},
    {"slug": "motor", "name": "1855KV"},
    {
        "slug": "jhemcu-ghf722-hd-aio-fcesc-40a-255-x-255mm",
        "name": "JHEMCU GHF722 HD AIO",
    },
    {"slug": "4", "name": "RHCP"},
    {"slug": "adl36-rtfn", "name": "Neon"},
    {"slug": "adl36-rtf", "name": "Green"},
    {"slug": "adl30", "name": "ADL30"},
    {"slug": "adl36", "name": "ADL36"},
    {"slug": "camera", "name": "PHOENIX"},
    {"slug": "unicorn", "name": "3-Turn"},
    {"slug": "18650", "name": "18650"},
    {"slug": "d100neo", "name": "D100neo"},
    {"slug": "lhcp", "name": "LHCP"},
    {"slug": "imars-d300", "name": "Black"},
    {"slug": "tattu-v50", "name": "Tattu V5.0, 1400mAh, 6S, 150C"},
    {"slug": "2s", "name": "2s"},
    {"slug": "t8", "name": "T8"},
    {"slug": "black", "name": "black"},
    {"slug": "2207", "name": "2207"},
    {"slug": "white", "name": "white"},
    {"slug": "t12", "name": "T12"},
    {"slug": "rrotek35", "name": "RroTek35"},
    {"slug": "evo", "name": "Evo"},
    {"slug": "60w", "name": "60W"},
    {"slug": "imarsd300", "name": "White"},
    {"slug": "d6-pro", "name": "D6 pro"},
    {"slug": "rhcp-15cm", "name": "RHCP (15cm)"},
    {"slug": "rhcp10cm", "name": "RHCP(10cm)"},
    {"slug": "lhcp-15cm", "name": "LHCP (15cm)"},
    {"slug": "baby-ratel-2", "name": "Baby Ratel 2"},
    {"slug": "foxwhoop", "name": "foxwhoop"},
    {"slug": "nano-rx", "name": "Nano Rx"},
    {"slug": "dmkr-fpv-monitor", "name": "DMKR FPV Monitor"},
    {"slug": "purple", "name": "3.6 ( purple)"},
    {"slug": "clear-gray", "name": "3.6(Clear Gray)"},
    {"slug": "clear-green", "name": "3.6(Clear Green)"},
    {"slug": "dual-band-t-antenna", "name": "Dual-band T Antenna"},
    {"slug": "dual-band-t-antenna-zyyaq", "name": "Dual-Band T Antenna"},
    {"slug": "black-dbffh", "name": "black"},
    {"slug": "3clear-gray", "name": "3.5(Clear Gray )"},
    {"slug": "35pink", "name": "3.5(pink)"},
    {"slug": "10x6e", "name": "1060E"},
    {"slug": "5-packets", "name": "5 packets"},
    {"slug": "9045", "name": "9045"},
    {"slug": "airplane-propellers", "name": "9060"},
    {"slug": "8060", "name": "8060"},
    {"slug": "8040", "name": "8040"},
    {"slug": "7060", "name": "7060"},
    {"slug": "elrs-lite-rx", "name": "ELRS Lite RX"},
    {"slug": "xt60-to-xt30", "name": "XT60 to XT30"},
    {"slug": "5050", "name": "5050"},
    {"slug": "es08maii", "name": "ES08MAII"},
    {"slug": "6055", "name": "6055"},
    {"slug": "7050", "name": "7050"},
    {"slug": "teal", "name": "Teal"},
    {"slug": "7-black-durable", "name": "7 (Black Durable)"},
    {"slug": "5-nd-filters-set", "name": "5 ND Filters Set"},
    {"slug": "7-light-grey", "name": "7 (Light Grey)"},
    {"slug": "gopro-bag", "name": "Gopro Bag"},
    {"slug": "goggles2-cable", "name": "Goggles2 Cable"},
    {"slug": "3800kv", "name": "4pcs - 3800kv"},
    {"slug": "nd8", "name": "ND8"},
    {"slug": "4x200mm-black", "name": "4mmX200mm Black"},
    {"slug": "neon", "name": "Nazgul F5"},
    {"slug": "ble-nano-3", "name": "BLE Nano 3"},
    {"slug": "vapor-x5", "name": "Vapor X5"},
    {"slug": "tattu-850mah-v50-150c", "name": "Tattu V5.0, 6S, 850mAh, 150C"},
    {"slug": "buzzer", "name": "Buzzer"},
    {"slug": "5-pb-j", "name": "1 packet"},
    {"slug": "t63mmx6gr-pc-tmount", "name": "T63MMX6GR-PC-Tmount"},
    {"slug": "yellow", "name": "Yellow"},
    {"slug": "5115kv", "name": "900KV"},
    {"slug": "gopro-filters", "name": "Gopro Filters"},
    {"slug": "lipo-bag", "name": "Lipo bag"},
    {"slug": "1300kv", "name": "4pcs 1300KV"},
    {"slug": "white-dkxen", "name": "White"},
    {"slug": "4s", "name": "15mmX220mm for 4S battery"},
    {"slug": "red", "name": "Red"},
    {"slug": "black-uqhsg", "name": "Black"},
    {"slug": "red-dbxku", "name": "Red"},
    {"slug": "peach-pink", "name": "Peach Pink"},
    {"slug": "prop-tool", "name": "Prop Tool"},
    {"slug": "elrs-24g-7-channel-pwm", "name": "ELRS 2.4G 7 Channel  PWM"},
    {"slug": "nano-2400-rx", "name": "Nano 2400 RX"},
    {"slug": "58ghz-linear-antenna", "name": "5.8GHZ  Linear Antenna"},
    {"slug": "8cm-cable", "name": "8cm cable"},
    {"slug": "elrs-915mhz", "name": "ELRS-915MHz"},
    {"slug": "o4-heatsink", "name": "O4 Heatsink"},
    {"slug": "45a-esc", "name": "45A ESC"},
    {"slug": "xa22121400kv", "name": "XA2212/1400kv"},
    {"slug": "vtx-1000-v23", "name": "VTX 1000 V2.3"},
    {"slug": "1-8s-battery-checker", "name": "1-8S Battery Checker"},
    {"slug": "xt-60-e", "name": "XT-60 E"},
    {"slug": "pandarc-led-strip-5v-led-0539", "name": "PandaRC Led Strip 5V LED-0539"},
    {"slug": "jhe20b-finder", "name": "jHE20B  Finder"},
    {"slug": "6s", "name": "6S"},
    {"slug": "xt60-to-type-c-100w-pd-cable", "name": "XT60 to Type-C 100W PD Cable"},
    {"slug": "1280e", "name": "1280E"},
    {"slug": "xt60-to-xt30-hctrh", "name": "XT60 to XT30"},
    {"slug": "er8", "name": "ER8"},
    {"slug": "hop-up-opions-car-light", "name": "Hop up opions car light"},
    {"slug": "20cm", "name": "20cm"},
    {"slug": "8cm", "name": "8cm"},
    {"slug": "15cm", "name": "15cm"},
    {"slug": "m-5-props-nuts-4pcs", "name": "M-5 props Nuts (4pcs)"},
    {"slug": "915-mhz-antenna", "name": "915 MHz Antenna"},
    {"slug": "camera-plate-soft-mount", "name": "Camera Plate Soft Mount"},
    {"slug": "1800kv-2207-motors", "name": "1800KV 2207 Motors"},
    {
        "slug": "xt60-to-xt30-charging-adapter-without-cable",
        "name": "XT60 to XT30 Charging Adapter without cable",
    },
]

print(
    len(uat_db_product_variant) == len(prod_db_product_variant),
    f"uat_db_product_variant: {len(uat_db_product_variant)}, prod_db_product_variant: {len(prod_db_product_variant)}",
)

good_prod_slugs = []
bad_slugs = []

for i in uat_db_product_variant:
    uat_db_slug = i["slug"]
    uat_db_name = i["name"]

    not_found_slug_in_prod_db = uat_db_slug
    for j in prod_db_product_variant:
        prod_db_slug = j["slug"]
        prod_db_name = j["name"]
        if prod_db_slug == uat_db_slug and prod_db_name == uat_db_name:
            good_prod_slugs.append(prod_db_slug)
            not_found_slug_in_prod_db = None
            break

    if not_found_slug_in_prod_db is not None:
        bad_slugs.append(not_found_slug_in_prod_db)

print(
    len(good_prod_slugs) == len(uat_db_product_variant),
    f"good_prod_slugs: {len(good_prod_slugs)}, uat_db_product_variant: {len(uat_db_product_variant)}",
)
print(len(bad_slugs) == 0, f"bad_slugs: {len(bad_slugs)}")
